### ISSUE TITLE
Collection Not visible from the icm tool

### ISSUE THREAD

**Issue by Obijuan** [cavearr/icecrystal#19]
Currently this collection can not be seen and installed from the icm tool  

If you want it to be installed from icm you should follow these steps:
1. Rename the master branch to main (It can be done very easily from the github interface: Click on "master" and select: "View all branches". Then click on the "..." on the right and select Rename branch. Write the new branch name: "main". That's it)
2.  Create a new release with the name "v1.0.0"

**Comment by cavearr** [comment]
Done!

**Comment by Obijuan** [comment]
The name given to the release is not correct. Is should be "v1.0.0" (Currently it is "v1.0.0-Nucleation", and icm cannot detect it)

**Comment by cavearr** [comment]
I had tried with v1.0.0 and v0.1.0 but both fails too.

**Comment by Obijuan** [comment]
OK. Forget about it. I will fork it in FPGAwars and debug from there
